### ISSUE TITLE
The Connectable Manifesto Whitepaper

### ISSUE THREAD

**Issue by sxysun-zz** [Yaindrop/connectable.rarea.net#1]
Based on the manifesto, maybe the foundation can issue Connectivity Token (CNT) to incentivize developers to engineer connectable services. 

Consider an initial coin offering to developers around the globe, by exchanging their fiat money (USD) or stable coins (Tether) for CNT, they can help the Connectable community to initiate large-scale public advocation plans, bring the big companies' syndicate down and build a completely decentralized, connectable software experience for all. 

This ICO will leverage the manifesto's community with a global, on-demand workforce and find expert freelance developers to design test, code, and build their own project. Or have big companies have their direct connectable integration. 

Along with freedom and better software experience, financial independence and be reached in the meantime. With CNT, we can crowdfund open-source startups or projects, and, in the process, allow the developers and supporters of this manifesto to own an equity share in it to receive massive amounts of future dividends. 

The token will be based on the ERC20 standard and be formally verified of its correctness and free of vulnerabilities such as re-entrancy attacks. The token is planned to go on major crypto exchanges like Bitfinex or Binance.

**Comment by sxysun-zz** [comment]
I strongly recommend adding the above whitepaper proposal to the website. 

It will help us make the world a better world, by establishing connectable software services and bring CNT token holders financial independence!!!

**Comment by yaindrop** [comment]
While this proposal can look promising, I cannot see any reason why anyone would exchange their currency for CNT when the whole Connectable ecosystem is only on paper. This proposal may be reconsidered after the Connectable community has gained enough significance with reasonable amount of active developers and users.

**Comment by sxysun-zz** [comment]
> While this proposal can look promising, I cannot see any reason why anyone would exchange their currency for CNT when the whole Connectable ecosystem is only on paper. This proposal may be reconsidered after the Connectable community has gained enough significance with reasonable amount of active developers and users.

Without proper initial funding, the manifesto will never gain enough public attention. And the best way to achieve the menifesto's goal of building a large ecosystem is by establishing the "connectable" idea as a promising investment. Only when the idea is securitized and turned into a financial product,, will people pay attention to it and give proper support by exchanging fiat money for an equity share of the virtualized "menifesto" 

Once we receive enough of the token holder's fiat money, we can initiate public relations campaigns and go around the globe to do tech talks to pitch the idea!

**Comment by yaindrop** [comment]
> 
> 
> > While this proposal can look promising, I cannot see any reason why anyone would exchange their currency for CNT when the whole Connectable ecosystem is only on paper. This proposal may be reconsidered after the Connectable community has gained enough significance with reasonable amount of active developers and users.
> 
> Without proper initial funding, the manifesto will never gain enough public attention. And the best way to achieve the menifesto's goal of building a large ecosystem is by establishing the "connectable" idea as a promising investment. Only when the idea is securitized and turned into a financial product,, will people pay attention to it and give proper support by exchanging fiat money for an equity share of the virtualized "menifesto"
> 
> Once we receive enough of the token holder's fiat money, we can initiate public relations campaigns and go around the globe to do tech talks to pitch the idea!

This claim is not supported by most of the current successful open-source projects. 

The Connectable Manifesto has no desire for making profits. Although it has no authority to restrain developers who agree with the manifesto, it is aimed at starting a non-commercial open-source community which provides connectable software services voluntarily.
